name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  limit-coverage:
    description: 'Lower of coverage'
    required: false
    default: "0"
  color-under-limit:
    description: 'Color under limit'
    required: false
    default: "#e32323"
  color-over-limit:
    description: 'Color over limit'
    required: false
    default: "#2db21b"
  badge-label:
    description: 'Badge label'
    required: false
    default: "coverage"
  badge-filename:
    description: 'Badge filename'
    required: false
    default: "badge.svg"
  badge-value:
    description: 'Badge value'
    required: true

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    # setup docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: launch docker image"
      run: docker run --rm 
        -e GITHUB_TOKEN=${{ github.token }} 
        -e GITHUB_ACTOR=${{ github.actor }} 
        -e GITHUB_ACTOR_ID=${{ github.actor_id }} 
        -e GITHUB_REPOSITORY=${GITHUB_REPOSITORY}.wiki 
        -e LIMIT_COVERAGE=${{ inputs.limit-coverage }} 
        -e COLOR_UNDER_LIMIT=${{ inputs.color-under-limit }} 
        -e COLOR_OVER_LIMIT=${{ inputs.color-over-limit }} 
        -e BADGE_LABEL=${{ inputs.badge-label }} 
        -e BADGE_FILENAME=${{ inputs.badge-filename }} 
        -e BADGE_VALUE=${{ inputs.badge-value }} 
        sgaunet/gh-action-test:latest
      shell: bash

