name: Use Random Number Action
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate-number:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: coverage
        id: coverage
        run: echo "COVERAGE_VALUE=80" >> $GITHUB_ENV

      - name: Generate coverage badge
        id: coverage-badge
        uses: ./.github/actions/gh-action-test
        with:
          limit-coverage: "80"
          badge-label: "coverage"
          badge-filename: "coverage-badge.svg"
          badge-value: "${COVERAGE_VALUE}"

      - name: Generate coverage badge2
        id: coverage-badge2
        uses: ./.github/actions/gh-action-test
        with:
          limit-coverage: "90"
          badge-label: "coverage"
          badge-filename: "coverage-badge2.svg"
          badge-value: "${COVERAGE_VALUE}"

      - name: Print url of badge
        run: |
          echo "Badge URL: ${{ steps.coverage-badge.outputs.badge-url }}"

      - name: Print url of badge2
        run: |
          echo "Badge URL: ${{ steps.coverage-badge2.outputs.badge-url }}"
